module Constants
  TIMEZONE = 'Central Time (US & Canada)'
  DAY_END = 1
  BUILD_MEETINGS = 27
  PRE_MEETINGS = 9
  PRE_HOURS = 15
  DEFAULT_LOGIN = "plexus@aasd.k12.wi.us"
  TEAM_NAME = 'NEW Apple Corps'
  TEAM_NUMBER = '93'
  SCHOOL_NAME_REPLACEMENT = 'School'
  GENDERS = ['Male', 'Female']
  FRESHMAN_HOURS = 70
  SOPHOMORE_HOURS = 87.5
  JUNIOR_HOURS = 87.5
  SENIOR_HOURS = 87.5
  LEADERSHIP_HOURS = 105
  FLEX_HOURS = 16
end
